name: 'Auto Assign'
on:
  pull_request:

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.0
        with:
          repo-token: "${{ secrets.TOKEN }}"
          addReviewers: true
          addAssignees: true
          reviewers:
            - rdhoju
            - rmsh03dhj
          numberOfReviewers: 1
